SELECT
    dd.encounter_id,
    dd.patient_nbr,
	dd.race,
    dd.gender,
	dd.age,
    dd.weight,
	dd.admission_type_id,
	dd.discharge_disposition_id,
	dd.admission_source_id,
	dd.time_in_hospital,
	dd.payer_code,
	dd.medical_specialty,
	dd.num_lab_procedures,
	dd.num_procedures ,
	dd.num_medications ,
	dd.number_outpatient ,
	dd.number_emergency ,
	dd.number_inpatient ,
	dd.diag_1 ,
	dd.diag_2 ,
	dd.diag_3 ,
	dd.number_diagnoses,
	md.max_glu_serum,
	md.A1Cresult,
	md.metformin,
	md.repaglinide,
	md.nateglinide,
	md.chlorpropamide,
	md.glimepiride,
	md.acetohexamide,
	md.glipizide,
	md.glyburide,
	md.tolbutamide,
	md.pioglitazone,
	md.rosiglitazone,
	md.acarbose,
	md.miglitol,
	md.troglitazone,
	md.tolazamide,
	md.examide,
	md.citoglipton,
	md.insulin,
	md."glyburide-metformin",
	md."glipizide-metformin",
	md."glimepiride-pioglitazone",
	md."metformin-rosiglitazone",
	md."metformin-pioglitazone",
	md.change,
	md.diabetesMed,
	md.readmitted
INTO diabetic_data_complete	
FROM 
	"diabetic_d" dd
LEFT JOIN "medications" md
ON  dd.encounter_id = md.encounter_id	